### ISSUE TITLE
vcs validate breaks when git remote prints message with empty lines

### ISSUE THREAD

**Issue by JosephBowkett** [dirk-thomas/vcstool#157]
Hi,

I'm using vcstool to manage repos from a Gitlab server that prints a large warning message (keystrokes logged etc etc) with each git push/pull/fetch, and several empty lines in the message break the vcs validate tool at line 616 of git.py, when hash_and_ref[0] is accessed but is empty.

An easy fix that restored function was to add the lines:
```
                if len(hash_and_ref) < 2:
                    continue
```
between lines 616 and 617 of git.py such that any empty or single element lines are ignored.

A follow up question while I'm typing this... was vcs validate ever intended to validate the state of the repo structure, rather than just the format of a repo file? When I first used it I assumed that's what it was doing, until I deleted one of the repos in the structure and vcs validate still reported that all was fine. This is more of a feature request, but wouldn't it make more sense for vcs validate to *both* check the format of the yaml file, *and* check that the existing structure matches that file?

Thanks,
Joseph

**Comment by dirk-thomas** [comment]
Thanks for the report. It seems the `validate` command needs the same fix / logic as was added in #154 for the `import` command. Please see #159 for a proposed fix.

> was vcs validate ever intended to validate the state of the repo structure, rather than just the format of a repo file?

No, the intention was to only check that the input file is formatted correctly. See its help message:
https://github.com/dirk-thomas/vcstool/blob/ce80335a68fecc694f41e17c18294229348b563b/vcstool/commands/validate.py#L20

> wouldn't it make more sense for vcs validate to both check the format of the yaml file, and check that the existing structure matches that file?

I would argue no since you want to be able to use `validate` without even having a working copy. I would suggest to run `export` and then compare the result with the existing repo file to check for differences.

**Comment by JosephBowkett** [comment]
Aaah okay, I checked to see if there was an existing issue for this on validate but didn't think to check for import or otherwise.

Fair point on validate, that does make more literal sense given the name. Yes, I currently run "vcs export" then visually compare that to my config file, but am considering writing a script to diff the current structure against a repo file, as that seems to be my most common use case recently. Would you have any interest in me submitting a PR if I added a verb for that? Named "vcs check" or similar, perhaps.

**Comment by dirk-thomas** [comment]
> Would you have any interest in me submitting a PR if I added a verb for that? Named "vcs check" or similar, perhaps.

That would be great. I would suggest naming it "compare" instead. "check" doesn't have a any context what is being checked imo.
