### ISSUE TITLE
git.py should not require a version to clone repo

### ISSUE THREAD

**Issue by kodyensley** [dirk-thomas/vcstool#19]
Git supports the notion of cloning a repository without specifying a branch. While vcstool allows the 'version' to be optional, git.py requires a version minatorily. This requires my vcstool import yaml file to specify a version/branch. It seems one should be able to clone the default branch from the source git repository. This way the owner of the remote repository can set the default branch.

**Comment by dirk-thomas** [comment]
For cloning a repo the first time this should be easy to implement.

Currently it requires a version since it also works when you already have a working copy cloned. Then `vcstool` needs to check if the version checked out is the same as requested in the yaml file and if not switch to the desired version.

It looks like with some more logic for the second case the "default" remote HEAD can be determined to make the version fully optional. I will look into creating a patch for this in the near future.

**Comment by dirk-thomas** [comment]
I have created pull request #21 to implement the feature you requested. Can you please give it a try and confirm that it works for your use case?

**Comment by dirk-thomas** [comment]
Closed by #21.

**Comment by kodyensley** [comment]
Thank you for your work on this. I look forward to testing this version when it makes its way into apt.

**Comment by dirk-thomas** [comment]
The Debian package is already available: http://packages.ros.org/ros/ubuntu/pool/main/p/python-vcstool/
