### ISSUE TITLE
vcstool status for anywhere nested in the workspace

### ISSUE THREAD

**Issue by PeterMitrano** [dirk-thomas/vcstool#199]
With wstool I really liked that I could just type wstool anywhere and see the status. My main reason for working this way was that I wanted to commit/push various things, and running just wstool from anywhere would just me which repos were dirty so I can go look at them.

I would love to have something like this in vcstool. Right now it only shows the status of the repo I'm in.

I'm not sure I'd find the time to PR something like this, at least not without some pointers and where to start with implementation.

**Comment by dirk-thomas** [comment]
Since `vcstool` doesn't have any state in the filesystem (which `wstool` does) I don't see how a feature like this could be implemented. The decision to *not* store information in the filesystem is intentional - e.g. to not duplicate information which might get out-of-sync.

I will go ahead and close the ticket for now. Please feel free to continue commenting. If you have a specific proposal how to implement this I am happy to reconsider. I would rely on a pull request though since I am not actively developing this tool anymore.
