### ISSUE TITLE
Release 0.2.16 or newer

### ISSUE THREAD

**Issue by 130s** [dirk-thomas/vcstool#220]
0.2.15 was made in 2020/10.

Personally I'd particularly like to see #218 resolved.

**Comment by dirk-thomas** [comment]
I just release the current state of the repo as 0.3.0 (since Python 2.7 and 3.4 support were dropped since the previous release).

I currently can't promise when I will be able to spend time on (reviewing) any tickets. Whenever that happens I will try to make timely releases afterwards to make the changes available from a released version.
