### ISSUE TITLE
tar extraction fails on Windows

### ISSUE THREAD

**Issue by bbaillio** [dirk-thomas/vcstool#27]
The os-specific separator is not used when extracting tarballs in python. So, on windows, all files are using the '/' separator. So in tar.py, the file extraction/replacement in get_members fails to work properly.
By removing the os.sep from the prefix, the code works cross-platform.
```python
def get_members(tar, prefix):
    for tar_info in tar.getmembers():
        if tar_info.name.startswith(prefix):
            tar_info.name = tar_info.name[len(prefix)+1:] # new +1 here to compensate
            yield tar_info
prefix = command.version #+ os.sep
tar.extractall(self.path, get_members(tar, prefix))
```

I've made this change locally on Windows and Linux and they both work. Maybe you can think of a more elegant solution.

**Comment by dirk-thomas** [comment]
Thanks for reporting the problem on Windows.

The `startswith` must check with a path separator otherwise it might match unrelated paths which start with the same prefix but have additional characters. Therefore your proposed patch doesn't work correctly.

Please see e978fe0427f0d40127b565f99e96fc4fdc82466a for the patch I just committed. Please comment if it doesn't address your problem.
