### ISSUE TITLE
Specifying Linux, Mac, or Windows specific repositories

### ISSUE THREAD

**Issue by geoffviola** [dirk-thomas/vcstool#32]
Are there any plans to support different dependencies on Linux, Mac, or Windows? This feature would be especially useful, if the tool downloads tar files with compiled artifacts.

**Comment by dirk-thomas** [comment]
I am not sure I understand your request. Can you please elaborate on your use case / what you would like to do.

**Comment by geoffviola** [comment]
Sure. This tool says it is intended for dealing with source code from other repositories. It supports downloading and unpacking tar files. I'm wondering if this tool is meant to support binaries.

It is pretty easy to put compiled libraries in a tar file. Unfortunately, the binaries are dependent on compiler version, compiler flags, and OS. I'm wondering if it makes sense for this tool to only download a tar file based on the OS that the script is run. 

A short term work around would be to download all of the dependencies. But it seems wasteful to get dependencies that won't be used.

**Comment by dirk-thomas** [comment]
I would phrase it like this: vcs doesn't care what is in the resources it is fetching. The users says what to fetch, the tool gets it.

In order to be able to differentiate between entries for different OS that information would need to be present in the `.repos` file which is being passed to `vcs import`. Arguably depending on the use case it would even make sense to select which repos should be fetched based on e.g. the Ubuntu version (e.g. on 15.10 and older you should clone `compat-repo` but not on any newer Ubuntu). Any criteria about the host system could decide if you need a certain resource or not. This kind of feature would require vcs tool to be aware of these criteria and formalize the conditions in the `.repos` file. That sounds like a lot of infrastructure for that use case :worried:

I am not convinced that `vcs` (in its core) should know about these. But this could e.g. be implemented on-top of `vcs`. Either as a separate tool or as a plugin / entry point to `vcs`. If a new command like `import-by-os` is not enough I would be happy to add the necessary hooks into the existing `import` command which allows an external plugin to parse the additional information from the `yaml` file and decide if a certain entry should be imported. What do you think about that approach?

A workaround right now for your scenario could be to split the resources into a `.repos` file containing the OS independent set as well as OS specific `.repos` files. But I guess you want something more streamlines :wink:

**Comment by dirk-thomas** [comment]
I will close this ticket for now since there is no action item to be done for now. Please feel free to comment here if there is anything which could be changed within `vcstool` to enable / make it easier to provide that functionality on top of the API of `vcstool`.
