### ISSUE TITLE
Raspberry Pi 3 restarts

### ISSUE THREAD

**Issue by silgon** [dirk-thomas/vcstool#49]
I was trying to follow the tutorial from https://github.com/ros2/ros2/wiki/Linux-Development-Setup . I was trying to do it with my raspberry pi. While doing `vcs-import src < ros2.repos`. I used the with the `--debug` flag, but it tells me nothing about the crash. 
```
DEBUG:vcstool.executor:ongoing ['src/eProsima/Fast-RTPS', 'src/ros2/urdfdom', 'src/ament/uncrustify', 'src/ros2/rmw_fastrtps', 'src/ros2/rosidl', 'src/ros2/realtime_support', 'src/eProsima/Fast-CDR', 'src/ament/ament_package', 'src/ament/ament_index', 'src/ros2/rosidl_typesupport', 'src/ros2/urdfdom_headers', 'src/ament/ament_python', 'src/ros2/poco_vendor', 'src/ros2/demos', 'src/ament/gtest_vendor', 'src/ros2/sros2', 'src/ros2/examples', 'src/ament/ament_lint', 'src/ros2/rclcpp', 'src/ros2/ros1_bridge']
Write failed: Broken pipe
```
In the previous line you see the las debug message and just after just a broken pipe because there is no more ssh connection with the RPI because it is restarting.

Any ideas?

**Comment by dirk-thomas** [comment]
I am not sure how `vcstool` could be triggering this.

* Can you reproduce the problem or did it only happen once?
* Do the system logs contain anything which hints why it restarted?

`vcs import` is basically just invoking multiple commands clone the various repos from the `.repos` file.

* If you can reproduce it can you bisect if it also happens with a subset of repositories in the file - maybe you can narrow it down to one specific one?
* Or maybe the Pi ran out of resources and crashed because of that?
* You could try to run the command with `--workers 1` to reduce the parallel load.

**Comment by silgon** [comment]
I think it is as you said, that the Pi was running out of resources. I saw that the N workers default value is `10` and I used `vcs-import --workers 4 src < ros2.repos`, which worked fine. For the problem, it happened not only once, it was every time I tried it, the Pi just shut down.

**Comment by dirk-thomas** [comment]
Can you please run the following command and post the output:

```
python -c "from multiprocessing import cpu_count; print(cpu_count())"
```

It might make sense to change the fixed default value to something more specific to the system it is running on.

**Comment by silgon** [comment]
`4` for the RPI.

**Comment by dirk-thomas** [comment]
Please see #50 which should choose the number of default workers based on your cpu count.

**Comment by silgon** [comment]
Seems a nice workaround to select it based on the number of CPUs. Thanks! ;)
