### ISSUE TITLE
Add option to `import` to retry clone of repositories until success or timeout

### ISSUE THREAD

**Issue by sloretz** [dirk-thomas/vcstool#52]
Some ci builds fail while using vcs to download dependencies because of temporary network issues ([example](http://ci.ros2.org/view/nightly/job/nightly_linux_debug/577/console)). 
 
```
07:36:31 === src/eProsima/Fast-RTPS (git) ===
07:36:31 Could not clone repository 'https://github.com/eProsima/Fast-RTPS.git': Cloning into '.'...
07:36:31 error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
07:36:31 fatal: The remote end hung up unexpectedly
07:36:31 fatal: early EOF
07:36:31 fatal: index-pack failed
```

I suspect this would had succeeded if vcs waited a few seconds and tried again. Adding an option to `import` which would retry cloning with some delay or increasing backoff may reduce the number of failing jobs on the build farm.

**Comment by dirk-thomas** [comment]
Sounds like a useful improvement. Please try #53 which retries the commands which utilize network access. The `tar` and `zip` types are already using a retry logic with a fixed number of retries. I didn't update those since they seemed sufficient until now.

As an alternative both could use a default retry or both could only used an optionally passed retry count.
