### ISSUE TITLE
For branding reasons, there should be a dash between vcs and tool.

### ISSUE THREAD

**Issue by calvertdw** [dirk-thomas/vcstool#56]
**vcs-tool** is probably a better name for this repository. The commands all have dashes, (vcs-branch, vcs-custom, etc.) and the main command is **vcs** and not **vcstool**, so I think there would be no confusion there.

**Comment by dirk-thomas** [comment]
Since the Python package name is [vcstool](https://pypi.python.org/pypi/vcstool) and it would be a breaking change to rename that I will keep the repository name the same as the Python package.

The commands contain the dashes are only used during development when not installing the Python package so those should affect the naming.
