### ISSUE TITLE
Git flow init pauses with no output

### ISSUE THREAD

**Issue by calvertdw** [dirk-thomas/vcstool#84]
When I use the commands below I would expect to be able to initialize each repository to git flow one by one using the `w 1` option. However, nothing ever prints out and the process pauses forever.
```
~/dev $ vcs import < robots.repos
~/dev $ vcs custom -w 1 robots --args flow init
```

My `.repos` file is structured like:
```
repositories:
  robots/project-1:
    type: git
    url: https://path.git
    version: master
  robots/project-2:
    type: git
    url: https://path.git
    version: develop
```

Upon keyboard interruption:
```
~/dev $ vcs custom -w 1 robots --args flow init
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\vcs.exe\__main__.py", line 9, in <module>
  File "c:\python37\lib\site-packages\vcstool\commands\vcs.py", line 23, in main
    return entrypoint(args)
  File "c:\python37\lib\site-packages\vcstool\commands\custom.py", line 84, in main
    debug_jobs=args.debug)
  File "c:\python37\lib\site-packages\vcstool\executor.py", line 103, in execute_jobs
    (job, result) = result_queue.get()
  File "c:\python37\lib\queue.py", line 170, in get
    self.not_empty.wait()
  File "c:\python37\lib\threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt
```

Using `vcs 0.1.36` and `git version 2.20.1.windows.1`.

**Comment by dirk-thomas** [comment]
The command `git flow init` is interactive by default but `vcstool` doesn't support passing through `stdin` at the moment and only outputs the process output after the process has finished (e.g. since it supports suppressing the output depending on the options).

The only workaround at the moment is to invoke the custom command in a way that it becomes non-interactive, e.g. `vcs custom -w 1 robots --args flow init -d`.

Supporting interactive commands would certainly be an option (when processing repos sequentially) but that would be a major feature development.

**Comment by calvertdw** [comment]
Defaults work for me! Did not know about the `-d` argument. I searched for a while, but just now found some documentation on the arguments.

https://github.com/nvie/gitflow/wiki/Command-Line-Arguments
