### ISSUE TITLE
Easier ways to create repository collections

### ISSUE THREAD

**Issue by calvertdw** [dirk-thomas/vcstool#97]
I find myself frequently creating unique collections of repositories. In both the ROS workspace framework and our own framework for Java software, one may select a set of repositories to build from source rather than linking to pre-compiled versions.

The fastest way to initialize a collection is to `mkdir -p` and `git clone` by hand, so I often skip the step to create the `.repos` file. Additionally, I find that I'm copying URLs from a browser window and pasting into `git clone`.

I was wondering if you had any recommended solutions to quickly creating a `.repos` file.

One idea I had was a web browser plugin in which right-clicking a VCS URI (such as a `.git` link) would provide a context menu entry to "Add to Workspace". It could provide a setting for default workspaces directory and automatically creating and modifying the `.repos` files. Maybe also a link to "Open Workspace in Terminal" once you're done.

I was just hoping to bounce off this idea and I didn't quite know where to put it.

**Comment by dirk-thomas** [comment]
> I was wondering if you had any recommended solutions to quickly creating a .repos file.

In the ROS ecosystem the tool [rosinstall_generator](https://github.com/ros-infrastructure/rosinstall_generator) can generate the yaml file for you. You only need to pass the package names (and the ROS distro) and it not only collects the repo information but also optionally the repos of all ROS dependencies.

> One idea I had was a web browser plugin ...

Sounds interesting. For my personal workflow I am not sure if I would see enough benefit from such a plugin. I usually clone the repos using the command line and then after having a set export a repos file using `vcs export`.

I will close the ticket for now since there is no actionable item for this repo. Please feel free to continue commenting.
